In [1]:
import numpy as np
import pandas as pd
import yaml
import os

In [2]:
from nba_api.stats.endpoints.commonallplayers import CommonAllPlayers
from nba_api.stats.endpoints import leaguedashplayerstats

In [3]:
import pickle
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

In [4]:
all_players = CommonAllPlayers().common_all_players.get_data_frame()

In [5]:
player_stats = leaguedashplayerstats.LeagueDashPlayerStats(season_type_all_star='Playoffs').get_data_frames()[0]

In [5]:
player_stats[['PLAYER_NAME','PTS']].query('PLAYER_NAME=="Kyrie Irving"')

      PLAYER_NAME  PTS
135  Kyrie Irving   85

In [6]:
player_stats

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,CFID,CFPARAMS
0,203932,Aaron Gordon,Aaron,1610612743,DEN,26.0,5,1,4,0.200,...,125,39,67,172,60,23,3,68,5,"203932,1610612743"
1,1628988,Aaron Holiday,Aaron,1610612756,PHX,25.0,4,1,3,0.250,...,1,152,153,61,160,38,3,157,5,"1628988,1610612756"
2,1630174,Aaron Nesmith,Aaron,1610612738,BOS,22.0,2,1,1,0.500,...,1,184,198,75,193,38,3,197,5,"1630174,1610612738"
3,201143,Al Horford,Al,1610612738,BOS,35.0,7,5,2,0.714,...,202,89,47,23,29,7,3,36,5,"201143,1610612738"
4,1627936,Alex Caruso,Alex,1610612741,CHI,28.0,4,1,3,0.250,...,103,100,129,168,103,38,3,110,5,"1627936,1610612741"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,1630214,Xavier Tillman,Xavier,1610612763,MEM,23.0,8,5,3,0.625,...,132,108,105,189,101,38,3,105,5,"1630214,1610612763"
212,1629139,Yuta Watanabe,Yuta,1610612761,TOR,27.0,4,2,2,0.500,...,1,184,175,141,200,38,3,193,5,"1629139,1610612761"
213,203897,Zach LaVine,Zach,1610612741,CHI,27.0,4,1,3,0.250,...,93,60,58,202,69,19,3,66,5,"203897,1610612741"
214,1630192,Zeke Nnaji,Zeke,1610612743,DEN,21.0,2,0,2,0.000,...,43,184,182,64,200,38,3,193,5,"1630192,1610612743"
215,1630533,Ziaire Williams,Ziaire,1610612763,MEM,20.0,7,4,3,0.571,...,110,89,89,164,121,38,3,116,5,"1630533,1610612763"

In [6]:
dp_fn = '/Users/joeseibert/Personal/git/nbapointsleague/drafted_players_2022.yml'

In [7]:
with open(dp_fn) as file:
    league = yaml.load(file, Loader=yaml.FullLoader)

In [8]:
for n in league:
    for p in league[n]:
        ps = player_stats[['PLAYER_NAME','PTS']].query(f'PLAYER_NAME=="{p}"')
        if len(ps) == 0:
            print(p)

Jarrett Allen
Darius Garland

In [10]:
player_stats[['PLAYER_NAME','PTS']].query('PLAYER_NAME=="Luka Doncic"').to_numpy()

array([['Luka Doncic', 219]], dtype=object)

In [11]:
player_stats[['PLAYER_NAME','PTS']].query('PLAYER_NAME=="Luka Doncic"').to_numpy()[0]

array(['Luka Doncic', 219], dtype=object)

In [12]:
q,w = player_stats[['PLAYER_NAME','PTS']].query('PLAYER_NAME=="Kyrie Irving"').to_numpy()[0]

In [13]:
player_stats.query('TEAM_ABBREVIATION=="TOR"')

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,CFID,CFPARAMS
9,1629717,Armoni Brooks,Armoni,1610612761,TOR,23.0,4,2,2,0.500,...,1,184,198,141,203,38,3,203,5,"1629717,1610612761"
31,1628449,Chris Boucher,Chris,1610612761,TOR,29.0,6,2,4,0.333,...,121,65,69,71,75,23,3,75,5,"1628449,1610612761"
36,1630625,Dalano Banton,Dalano,1610612761,TOR,22.0,4,2,2,0.500,...,1,130,162,153,174,38,3,172,5,"1630625,1610612761"
67,1627832,Fred VanVleet,Fred,1610612761,TOR,28.0,4,1,3,0.250,...,110,108,82,200,71,38,3,74,5,"1627832,1610612761"
72,1629018,Gary Trent Jr.,Gary,1610612761,TOR,23.0,6,2,4,0.333,...,103,74,51,208,66,38,3,64,5,"1629018,1610612761"
84,1629067,Isaac Bonga,Isaac,1610612761,TOR,22.0,1,0,1,0.000,...,29,165,189,102,198,38,3,197,5,"1629067,1610612761"
129,203920,Khem Birch,Khem,1610612761,TOR,29.0,6,2,4,0.333,...,121,184,145,71,146,38,3,147,5,"203920,1610612761"
140,1630201,Malachi Flynn,Malachi,1610612761,TOR,24.0,6,2,4,0.333,...,71,138,198,91,182,38,3,183,5,"1630201,1610612761"
161,1628384,OG Anunoby,OG,1610612761,TOR,24.0,6,2,4,0.333,...,156,40,44,191,51,38,3,49,5,"1628384,1610612761"
166,1627783,Pascal Siakam,Pascal,1610612761,TOR,28.0,6,2,4,0.333,...,186,15,26,202,24,19,3,27,5,"1627783,1610612761"
174,1630173,Precious Achiuwa,Precious,1610612761,TOR,22.0,6,2,4,0.333,...,125,60,74,191,86,38,3,80,5,"1630173,1610612761"
181,1630567,Scottie Barnes,Scottie,1610612761,TOR,20.0,4,2,2,0.500,...,110,74,86,181,77,23,3,79,5,"1630567,1610612761"
190,1629004,Svi Mykhailiuk,Svi,1610612761,TOR,24.0,3,2,1,0.667,...,29,184,197,153,204,38,3,203,5,"1629004,1610612761"
192,201152,Thaddeus Young,Thaddeus,1610612761,TOR,33.0,6,2,4,0.333,...,84,138,137,128,120,38,3,128,5,"201152,1610612761"
212,1629139,Yuta Watanabe,Yuta,1610612761,TOR,27.0,4,2,2,0.500,...,1,184,175,141,200,38,3,193,5,"1629139,1610612761"

In [14]:
pts = 0
gps = 0
for n in league:
    pts = 0
    gps = 0
    print(n)
    for p in league[n]:
        try:
            pname, pt, gp = player_stats[['PLAYER_NAME','PTS', 'GP']].query(f'PLAYER_NAME=="{p}"').to_numpy()[0]
        except IndexError:
            pname = p
            pt = 0
            gp = 0
        print(pname, pt, gp)
        pts+=pt
        gps+=gp
    
    print(f'points: {pts}')
    print(f'gps: {gps}')
    print('\n')

Jono
Devin Booker 175 7
Desmond Bane 171 9
Jaylen Brown 159 7
Fred VanVleet 55 4
Brook Lopez 87 8
Cameron Johnson 109 10
Trae Young 77 5
Spencer Dinwiddie 125 10
Bones Hyland 46 5
Jonathan Kuminga 47 7
points: 1051
gps: 72


Drew
Giannis Antetokounmpo 237 8
Jimmy Butler 232 8
Jordan Poole 183 8
Pascal Siakam 137 6
Marcus Smart 85 6
Dillon Brooks 107 8
Andrew Wiggins 120 8
Aaron Gordon 69 5
Jalen Brunson 235 10
Zach LaVine 77 4
points: 1482
gps: 71


Joe
Ja Morant 244 9
Chris Paul 198 10
Nikola Jokic 155 5
Luka Doncic 219 7
Karl-Anthony Towns 131 6
DeMar DeRozan 104 5
Seth Curry 58 4
Jarrett Allen 0 0
Jordan Clarkson 105 6
Derrick White 45 7
points: 1259
gps: 59


Con
Jayson Tatum 178 7
Joel Embiid 199 8
Donovan Mitchell 153 6
James Harden 198 10
Klay Thompson 161 8
Bojan Bogdanovic 108 6
Kyle Lowry 31 5
Al Horford 97 7
Bobby Portis 95 8
Monte Morris 70 5
points: 1290
gps: 70


Sam
Kevin Durant 105 4
Khris Middleton 29 2
Mikal Bridges 146 10
Kyrie Irving 85 4
Bam Adebayo 139 9
Jaren Jackson Jr. 131 9
Tyrese Maxey 220 10
Will Barton 69 5
Cameron Payne 49 10
Rudy Gobert 72 6
points: 1045
gps: 69


Julian
Deandre Ayton 187 10
Stephen Curry 221 8
Tyler Herro 132 9
Jrue Holiday 151 8
D'Angelo Russell 72 6
Anthony Edwards 151 6
Darius Garland 0 0
Gary Trent Jr. 92 6
Jae Crowder 105 10
CJ McCollum 133 6
points: 1244
gps: 69

In [21]:
# specifying which sheet to use
SCOPES = ['https://www.googleapis.com/auth/spreadsheets']
spreadsheet_id = '1M0r9xh3V2bEBan6zA7If3o6R8ZPq_ytCF2RTGirV5MQ'

# taken from Google Sheets API instructions
creds = None
# The file token.pickle stores the user's access and refresh tokens, and is
# created automatically when the authorization flow completes for the first
# time.
if os.path.exists('token.pickle'):
    with open('token.pickle', 'rb') as token:
        creds = pickle.load(token)
# If there are no (valid) credentials available, let the user log in.
if not creds or not creds.valid:
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    else:
        flow = InstalledAppFlow.from_client_secrets_file(
            'credentials.json', SCOPES)
        creds = flow.run_local_server(port=0)
    # Save the credentials for the next run
    with open('token.pickle', 'wb') as token:
        pickle.dump(creds, token)
        
service = build('sheets', 'v4', credentials=creds)
sheet = service.spreadsheets()

In [22]:
player_stats = leaguedashplayerstats.LeagueDashPlayerStats(season_type_all_star='Playoffs').get_data_frames()[0]

pts = []
gps = []
for n in league:
    pts = []
    gps = []
    pts_sheet_range = n+'!B2:B11'
    gps_sheet_range = n+'!C2:C11'
    for p in league[n]:
        try:
            pname, pt, gp = player_stats[['PLAYER_NAME','PTS','GP']].query(f'PLAYER_NAME=="{p}"').to_numpy()[0]
            pname = p
            pts.append([str(pt)])
            gps.append([str(gp)])
        except IndexError:
            pname = p
            pt = 0
            gp = 0
            pts.append([str(pt)])
            gps.append([str(gp)])
        
    ptsvalues = pts
    gpsvalues = gps
    
    data = [
        {
            'range': pts_sheet_range,
            'values': ptsvalues
        },
        # Additional ranges to update ...
    ]
    body = {
        'valueInputOption': 'USER_ENTERED',
        'data': data
    }
    result = service.spreadsheets().values().batchUpdate(
        spreadsheetId=spreadsheet_id, body=body).execute()
    
    data = [
        {
            'range': gps_sheet_range,
            'values': gpsvalues
        },
        # Additional ranges to update ...
    ]
    body = {
        'valueInputOption': 'USER_ENTERED',
        'data': data
    }
    result = service.spreadsheets().values().batchUpdate(
        spreadsheetId=spreadsheet_id, body=body).execute()

In [23]:
drafted_players = np.array(list(league.values())).flatten()

In [24]:
udfa = player_stats[['PLAYER_NAME','PTS','GP']].sort_values('PTS',ascending=False).query(
            'PLAYER_NAME not in @drafted_players').iloc[:10].to_numpy()

In [25]:
pnames = []
pts = []
gps = []
pnames_sheet_range = 'Undrafted Players!A2:A11'
pts_sheet_range = 'Undrafted Players!B2:B11'
gps_sheet_range = 'Undrafted Players!C2:C11'

for p in udfa:
    pname, pt, gp = p
    pnames.append([str(pname)])
    pts.append([str(pt)])
    gps.append([str(gp)])
    
pnamesvalues = pnames
ptsvalues = pts
gpsvalues = gps
    
data = [
    {
        'range': pnames_sheet_range,
        'values': pnamesvalues
    },
    # Additional ranges to update ...
]
body = {
    'valueInputOption': 'USER_ENTERED',
    'data': data
}
result = service.spreadsheets().values().batchUpdate(
    spreadsheetId=spreadsheet_id, body=body).execute()
    
data = [
    {
        'range': pts_sheet_range,
        'values': ptsvalues
    },
    # Additional ranges to update ...
]
body = {
    'valueInputOption': 'USER_ENTERED',
    'data': data
}
result = service.spreadsheets().values().batchUpdate(
    spreadsheetId=spreadsheet_id, body=body).execute()

data = [
    {
        'range': gps_sheet_range,
        'values': gpsvalues
    },
    # Additional ranges to update ...
]
body = {
    'valueInputOption': 'USER_ENTERED',
    'data': data
}
result = service.spreadsheets().values().batchUpdate(
    spreadsheetId=spreadsheet_id, body=body).execute()

In [26]:
udfa

array([['Dorian Finney-Smith', 211, 18],
       ['Grant Williams', 207, 24],
       ['Tobias Harris', 203, 12],
       ['Max Strus', 196, 18],
       ['Reggie Bullock', 190, 18],
       ['Draymond Green', 176, 22],
       ['Brandon Ingram', 162, 6],
       ['Victor Oladipo', 159, 15],
       ['Maxi Kleber', 157, 18],
       ['Brandon Clarke', 148, 12]], dtype=object)

In [32]:
player_stats[['PLAYER_NAME','PTS']].sort_values('PTS', ascending=False).head(25).reset_index()

    index            PLAYER_NAME  PTS
0     104           Jayson Tatum  615
1     188          Stephen Curry  602
2     102           Jaylen Brown  554
3     139            Luka Doncic  475
4     107           Jimmy Butler  466
5     132          Klay Thompson  419
6      93          Jalen Brunson  388
7      75  Giannis Antetokounmpo  380
8     116           Jordan Poole  373
9       7         Andrew Wiggins  363
10    144           Marcus Smart  324
11      3             Al Horford  277
12     12            Bam Adebayo  266
13    187      Spencer Dinwiddie  255
14    205           Tyrese Maxey  249
15     87              Ja Morant  244
16    108            Joel Embiid  236
17     54           Devin Booker  233
18     49          Deandre Ayton  233
19    120           Jrue Holiday  229
20     32             Chris Paul  228
21     53           Desmond Bane  225
22     95           James Harden  223
23     59    Dorian Finney-Smith  211
24     78         Grant Williams  207

In [174]:
pts = []
gps = []
for n in league:
    pts = []
    gps = []
    pts_sheet_range = n+'!B2:B11'
    gps_sheet_range = n+'!C2:C11'
    for p in league[n]:
        try:
            pname, pt, gp = player_stats[['PLAYER_NAME','PTS','GP']].query(f'PLAYER_NAME=="{p}"').to_numpy()[0]
            pname = p
            pts.append([str(pt)])
            gps.append([str(gp)])
        except IndexError:
            pname = p
            pt = 0
            gp = 0
            pts.append([str(pt)])
            gps.append([str(gp)])
        
    ptsvalues = pts
    gpsvalues = gps

In [176]:
pd.DataFrame(udfa, columns=['player_name', 'points', 'games_played'])

           player_name points games_played
0       Brandon Ingram     89            3
1           OG Anunoby     83            4
2        Tobias Harris     72            4
3       Nikola Vucevic     67            3
4       Brandon Clarke     61            4
5          Maxi Kleber     55            4
6          Bruce Brown     54            3
7    Bogdan Bogdanovic     53            3
8       Reggie Bullock     49            4
9  Dorian Finney-Smith     48            4

In [268]:
lg_pts = {}

for n in league:
    lg_pts.setdefault(n, [])
    for p in league[n]:
        try:
            pstats = player_stats[['PLAYER_NAME','PTS','GP']].query(f'PLAYER_NAME=="{p}"').to_numpy()[0]
            lg_pts[n].append(tuple(pstats))
        except IndexError:
            pstats = (p, 0, 0)
            lg_pts[n].append(pstats)
    lg_pts[n] = np.array(lg_pts[n],
                         dtype=[('player_name', 'U50'), ('points', 'i4'), ('games_played', 'i4')])

In [270]:
lg_pts['Jono']

array([('Devin Booker', 56, 2), ('Desmond Bane', 93, 4),
       ('Jaylen Brown', 68, 3), ('Fred VanVleet', 55, 4),
       ('Brook Lopez', 54, 4), ('Cameron Johnson', 45, 4),
       ('Trae Young', 66, 4), ('Spencer Dinwiddie', 64, 4),
       ('Bones Hyland', 42, 4), ('Jonathan Kuminga', 10, 3)],
      dtype=[('player_name', '<U50'), ('points', '<i4'), ('games_played', '<i4')])

In [285]:
jonopts = pd.DataFrame(lg_pts['Jono'])
sampts = pd.DataFrame(lg_pts['Sam'])

In [275]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objs as go
import dash_table

/Users/joeseibert/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`

/Users/joeseibert/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/joeseibert/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning:
The dash_table package is deprecated. Please replace
`import dash_table` with `from dash import dash_table`

Also, if you're using any of the table format helpers (e.g. Group), replace
`from dash_table.Format import Group` with
`from dash.dash_table.Format import Group`
  """

In [291]:
########### Define your variables ######
myheading = "Points League"
mysubheading = "Jono"
tabtitle = 'python rocks'

########### Set up the data
# df = pd.read_csv(filename)
df1 = jonopts
df2 = sampts

########### Initiate the app
external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']
# app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
app = dash.Dash(__name__)
server = app.server
app.title=tabtitle

########### Set up the layout
app.layout = html.Div(children=[
    html.H1(myheading),
    html.H3(mysubheading),

    dash_table.DataTable(
        id='table1',
        columns=[{"name": i, "id": i} for i in df1.columns],
        data=df1.to_dict('records'),
    ),
    html.H3("Sam"),
    dash_table.DataTable(
        id='table2',
        columns=[{"name": i, "id": i} for i in df2.columns],
        data=df2.to_dict('records'),
    ),
    ]
)

In [292]:
app.run_server()

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [25/Apr/2022 11:34:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2022 11:34:18] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2022 11:34:18] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2022 11:34:18] "GET /_favicon.ico?v=2.1.0 HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2022 11:34:18] "GET /_dash-component-suites/dash/dash_table/async-highlight.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2022 11:34:18] "GET /_dash-component-suites/dash/dash_table/async-table.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2022 12:35:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2022 12:35:26] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2022 12:35:26] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2022 12:35:26] "GET /_favicon.ico?v=2.1.0 HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2022 12:35:26] "GET /_dash-component-suites/dash/dash_table/async-highlight.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Apr/2022 12:35:26] "GET /_dash-component-suites/dash/dash_table/async-table.js HTTP/1.1" 200 -