In [56]:
import numpy as np
import pandas as pd

In [145]:
from nba_api.stats.endpoints import playercareerstats
from nba_api.stats.static import players
from nba_api.stats.endpoints import commonplayerinfo
from nba_api.stats.endpoints.commonallplayers import CommonAllPlayers
from nba_api.stats.endpoints import playergamelog

In [21]:
big_fundamental = [player for player in nba_players
                   if player['full_name'] == 'Tim Duncan'][0]

In [24]:
big_fundamental

{'id': 1495,
 'full_name': 'Tim Duncan',
 'first_name': 'Tim',
 'last_name': 'Duncan',
 'is_active': False}

In [25]:
player_list = ['Damian Lillard','Kevin Durant','Russell Westbrook']

In [89]:
# Basic Request
player_info = commonplayerinfo.CommonPlayerInfo(player_id=2544)

In [90]:
player_info.common_player_info.get_data_frame()

,PERSON_ID,FIRST_NAME,LAST_NAME,DISPLAY_FIRST_LAST,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FI_LAST,PLAYER_SLUG,BIRTHDATE,SCHOOL,COUNTRY,...,TEAM_CITY,PLAYERCODE,FROM_YEAR,TO_YEAR,DLEAGUE_FLAG,NBA_FLAG,GAMES_PLAYED_FLAG,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER
0,2544,LeBron,James,LeBron James,"James, LeBron",L. James,lebron-james,1984-12-30T00:00:00,St. Vincent-St. Mary HS (OH),USA,...,Los Angeles,lebron_james,2003,2020,N,Y,Y,2003,1,1

In [61]:
player_info.player_headline_stats.get_data_frame()

   PLAYER_ID   PLAYER_NAME TimeFrame   PTS  AST  REB    PIE
0       2544  LeBron James   2020-21  22.8  6.5  7.5  0.165

In [74]:
from nba_api.stats.endpoints.commonallplayers import CommonAllPlayers

In [103]:
df = CommonAllPlayers().common_all_players.get_data_frame()

In [96]:
CommonAllPlayers().common_all_players.get_data_frame().query("DISPLAY_FIRST_LAST == 'Damian Lillard'")

,PERSON_ID,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FIRST_LAST,ROSTERSTATUS,FROM_YEAR,TO_YEAR,PLAYERCODE,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CODE,GAMES_PLAYED_FLAG,OTHERLEAGUE_EXPERIENCE_CH
2428,203081,"Lillard, Damian",Damian Lillard,1,2012,2020,damian_lillard,1610612757,Portland,Trail Blazers,POR,blazers,Y,00

In [93]:
player_info = commonplayerinfo.CommonPlayerInfo(player_id=203081)

In [101]:
player_info.player_headline_stats.get_json()

'{"headers": ["PLAYER_ID", "PLAYER_NAME", "TimeFrame", "PTS", "AST", "REB", "PIE"], "data": [[203081, "Damian Lillard", "2020-21", 24.0, 7.0, 4.3, 0.127]]}'

In [129]:
df.loc[df['DISPLAY_FIRST_LAST'].isin(player_list)]

1097    201142
2428    203081
4331    201566
Name: PERSON_ID, dtype: int64

In [105]:
from nba_api.stats.endpoints import playergamelog

In [119]:
playergamelog.PlayerGameLog(player_id = 203081,season=2020).get_data_frames()[0]

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22020,203081,0022000045,"DEC 28, 2020",POR @ LAL,W,36,10,16,0.625,...,4,4,5,0,1,5,1,31,-10,1
1,22020,203081,0022000029,"DEC 26, 2020",POR vs. HOU,W,41,11,28,0.393,...,4,5,9,1,0,5,1,32,7,1
2,22020,203081,0022000020,"DEC 23, 2020",POR vs. UTA,L,34,4,12,0.333,...,4,4,7,1,1,1,1,9,-21,1

In [124]:
from nba_api.stats.endpoints import playervsplayer

In [152]:
playervsplayer.PlayerVsPlayer(player_id=203081,vs_player_id=201142).get_data_frames()[0]

KeyboardInterrupt:

In [128]:
playergamelog.PlayerGameLog(player_id = 201142,season=2020).get_data_frames()[0]

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22020,201142,0022000032,"DEC 27, 2020",BKN @ CHA,L,36,9,15,0.600,...,3,3,4,0,1,3,3,29,7,1
1,22020,201142,0022000007,"DEC 25, 2020",BKN @ BOS,W,33,9,16,0.563,...,4,4,3,2,0,2,3,29,31,1
2,22020,201142,0022000001,"DEC 22, 2020",BKN vs. GSW,W,25,7,16,0.438,...,4,5,3,3,1,1,3,22,26,1

In [150]:
def get_player_id(player_list,common_all_players):
    player_array = []
    
    use_player_list = common_all_players.loc[common_all_players['DISPLAY_FIRST_LAST'].isin(player_list)]
    
    for index,row in use_player_list.iterrows():
        player_array.append({'player_name': row['DISPLAY_FIRST_LAST'],'player_id': row['PERSON_ID']})
        
    return player_array

In [151]:
get_player_id(player_list,df)

[{'player_name': 'Kevin Durant', 'player_id': 201142},
 {'player_name': 'Damian Lillard', 'player_id': 203081},
 {'player_name': 'Russell Westbrook', 'player_id': 201566}]

In [147]:
sheet_id = '16KJmOPm_2zAl2W1X2w265an-d7yMolOMfmITrTINsfI'